version: '3'

vars:
  APP_NAME: go-echo-backend
  CMD_DIR: ./cmd/go-echo
  BUILD_DIR: ./bin
  ENV_FILE: .env
  PORT: 8080

dotenv:
  - "{{.ENV_FILE}}"

tasks:
  run:
    desc: Run the Echo backend with environment variables from .env
    cmds:
      - go run {{.CMD_DIR}}

  build:
    desc: Build the Echo backend binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.APP_NAME}} {{.CMD_DIR}}

  tidy:
    desc: Tidy and verify Go modules
    cmds:
      - go mod tidy
      - go mod verify

  test:
    desc: Run all Go tests
    cmds:
      - go test ./... -v

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  watch:
    desc: Run backend with live reload (requires `air`)
    cmds:
      - air
